@startuml
start
:$./gradlew connectedCheck;
if (with -Pcucumber?) then (yes)
  :CucumberTestRunner;
  fork
    :onCreate();
    :parseTestTags;
    :parseTestScenario;
    :CucumberInstrumentationCore.create();
  fork again
    :onStart();
    :waitForIdleSync;
    :CucumberInstrumentationCore.start();
  end fork
else (no)
  :AndroidJUnitRunner;
endif

stop
@enduml